launguage: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t agent77/docker-react -f Dockerfile.dev .
  

script:
  - docker run -e CI=true agent77/docker-react npm run test
